-- ============================================================================
-- NiaCare — ALL PENDING MIGRATIONS, COMBINED FOR ONE-PASTE DEPLOYMENT
--
-- Generated by concatenating the 6 individually-reviewed pending changes,
-- in dependency-safe order, wrapped in a single transaction. Nothing here
-- is new SQL — every statement below is byte-identical to its source file:
--
--   1. supabase/migrations/20260901142812_appointment_pipeline.sql
--   2. supabase/migrations/20260902015936_facility_departments_services.sql
--   3. supabase/migrations/20260902041602_book_appointment_active_check.sql
--   4. fetch_queue_position()              — from supabase/schema.sql
--   5. fetch_patient_record_access_log()   — from supabase/schema.sql
--   6. supabase/migrations/20260902045354_audit_logs_facility_id.sql
--
-- STATUS: NOT YET APPLIED. This file was generated, not executed — running
-- it is a manual step you take in the Supabase SQL Editor.
--
-- ORDER MATTERS for item 4: fetch_queue_position() reads
-- appointments.called_at and the 'called'/'in_consultation' status values,
-- both of which only exist after item 1 (the appointment pipeline) runs.
-- This is a real dependency that was not documented until now — earlier
-- reports in this project incorrectly said fetch_queue_position() had no
-- dependencies; correcting that here. Item 1 is placed first in this file
-- specifically so item 4 works the first time it's called after this
-- script runs. All other items are mutually independent.
--
-- WHAT THIS DOES TO ALREADY-LIVE OBJECTS (read before running):
--   - Items 3 and 6 each replace the body of an already-live function
--     (book_appointment(), log_audit_event()) that the app already uses
--     today. Item 6 specifically DROPS and recreates log_audit_event()
--     (required — see its own comment below — a plain CREATE OR REPLACE
--     with a different parameter list would create a second, ambiguous
--     overload and break every existing caller via PGRST203). Everything
--     else only adds new, previously-absent tables/columns/functions.
--   - No existing data is deleted or rewritten anywhere in this file.
--
-- TRANSACTION SAFETY: wrapped in BEGIN / COMMIT below. If any statement in
-- this file fails, Postgres rolls back everything in this script — you
-- will not end up with only some of the 6 items applied. If you'd rather
-- apply items individually (recommended if you want to verify each one
-- before moving to the next), use the 4 separate files in
-- supabase/migrations/ plus the two schema.sql-only functions instead of
-- this combined file, and follow supabase/migrations/README.md.
--
-- PRE-FLIGHT (already checked read-only against the live database while
-- preparing this file — re-check if meaningful time has passed since):
--   - appointments: 2 total rows, statuses 'confirmed'/'cancelled' only —
--     no row would violate the new status check constraint or the new
--     partial unique index.
--   - doctor_profiles: 0 rows currently have a provider_id set — no
--     existing doctor is attached to any facility yet, so the new
--     department_id column and assign_doctor_department() start clean.
--   - facility_departments / facility_services: confirmed not to exist yet
--     (fresh read-only probe).
--   - log_audit_event: confirmed exactly one version live (5-arg) before
--     this file's DROP + CREATE in item 6.
--   - None of the 6 items were found live in this same pre-flight pass —
--     all 6 are still genuinely pending as of that check.
--
-- POST-DEPLOY VERIFICATION: run the queries at the bottom of this file
-- after it completes, and/or the more detailed per-item queries in each
-- source file's own header comment.
--
-- ROLLBACK: NOT automatic. If you need to undo this after it has
-- committed, you must manually reverse each item — there is no single
-- "undo" command. In particular, items 3 and 6 replaced a live function;
-- reverting them means re-running that function's PREVIOUS definition
-- (recoverable from this repository's git history prior to this session),
-- not just deleting something new.
-- ============================================================================

begin;

-- ============================================================================
-- ITEM 1 of 6: Appointment pipeline
-- Source: supabase/migrations/20260901142812_appointment_pipeline.sql
-- ============================================================================

-- ============================================================================
-- NiaCare — Appointment status pipeline (check-in / queue / consultation)
--
-- STATUS: NOT YET APPLIED to the live database as of this file's creation.
-- This file was extracted verbatim from supabase/schema.sql (the project's
-- single source-of-truth schema file) so it can be reviewed and applied on
-- its own, without re-running the rest of schema.sql. The content below is
-- byte-for-byte identical to the corresponding section of schema.sql — see
-- that file for the same objects in context with everything else.
--
-- WHAT THIS ADDS (all additive, nothing removed or renamed):
--   1. appointments_doctor_slot_unique — a partial unique index closing a
--      double-booking gap (a raw insert could bypass book_appointment()'s
--      own doctor_schedule-based protection). book_appointment() itself is
--      NOT modified.
--   2. 9 new nullable timestamp/actor columns on public.appointments.
--   3. appointments_status_check extended from 4 values to 8 (arrived,
--      called, in_consultation, no_show added; confirmed/in_queue/
--      completed/cancelled kept exactly as they were).
--   4. A new function patient_arrive_appointment().
--   5. check_in_appointment() replaced with an updated body (same name,
--      same signature — now also accepts 'arrived' as a valid starting
--      status, in addition to the existing 'confirmed').
--   6. Three new functions: call_patient(), start_consultation(),
--      complete_appointment_visit().
--   7. A new function mark_appointment_no_show().
--
-- WHY THIS IS SAFE:
--   - Every ALTER TABLE ... ADD COLUMN uses IF NOT EXISTS.
--   - The status check constraint is dropped and re-added by name
--     (appointments_status_check) rather than blindly appended, so
--     re-running this file is a no-op the second time.
--   - The unique index uses IF NOT EXISTS and is PARTIAL (excludes
--     cancelled rows and rows with no real doctor_profile_id), so it only
--     ever rejects a genuine live double-booking, never legitimate
--     cancel-and-rebook.
--   - Every function is CREATE OR REPLACE with an unchanged signature
--     (check_in_appointment) or a brand-new name — nothing is dropped.
--   - Every function is SECURITY DEFINER with SET search_path = public
--     and an explicit authorization check as its first real statement
--     (patient-only, provider-staff-at-the-same-facility, treating-doctor,
--     or admin — see each function body below) before touching any row.
--   - Pre-flight data was checked against the live database before this
--     was written (see the deployment README next to this file): 2 total
--     appointment rows existed, using only 'confirmed'/'cancelled', and
--     zero non-cancelled appointments had a real doctor_profile_id — so
--     neither the constraint change nor the unique index had any existing
--     row to conflict with at the time of writing. Re-run the pre-flight
--     queries in the README immediately before applying, since data may
--     have changed since.
--
-- HOW TO APPLY: see supabase/migrations/README.md in this same directory
-- for the exact Supabase SQL Editor steps and the post-deploy verification
-- queries. This file makes no network calls and was not executed by the
-- assistant that generated it — applying it is a manual, deliberate step.
-- ============================================================================

-- ============================================================================
-- Defense-in-depth against double-booking a doctor's slot.
--
-- book_appointment() below already prevents this for any caller that goes
-- through it (the doctor_schedule unique constraint + a conditional
-- ON CONFLICT ... WHERE is_booked = false upsert makes reserving a slot
-- atomic — two concurrent callers can't both win it). But appointments' own
-- RLS policy ("manageable by owner", checked only on patient_id) does not
-- require booking to go through that RPC — a client could INSERT into
-- public.appointments directly with the anon key and bypass the schedule
-- reservation entirely. This partial unique index closes that gap at the
-- table itself: no two non-cancelled appointments for the same doctor can
-- ever share a date+time, regardless of insert path. Partial (excludes
-- cancelled appointments and legacy/static-directory rows with no real
-- doctor_profile_id) so a cancelled+rebooked slot, or the pre-real-doctors
-- static directory, is never blocked.
--
-- Verified safe before adding: a read-only check against the live database
-- found zero non-cancelled appointments with a real doctor_profile_id at
-- all, so there is no existing duplicate data this index could conflict
-- with. CREATE UNIQUE INDEX would fail loudly (not corrupt data) if that
-- ever changed before this ran.
create unique index if not exists appointments_doctor_slot_unique
  on public.appointments (doctor_profile_id, appointment_date, time_slot)
  where status <> 'cancelled' and doctor_profile_id is not null;


-- ============================================================================
-- APPOINTMENT STATUS PIPELINE — reception check-in + patient
-- arrival + queue management (NiaCare "reduce waiting and congestion" phase).
--
-- Existing model before this block: 'confirmed' -> 'in_queue' -> 'completed'
-- (the last transition was never actually wired to any code path — nothing
-- ever set status = 'completed'), plus 'cancelled'. That's too coarse for
-- the real patient journey (self-arrival, reception confirmation, being
-- called, consultation in progress) and had no no-show state at all.
--
-- New, additive pipeline (old values kept, 4 added):
--   confirmed -> arrived -> in_queue -> called -> in_consultation -> completed
--                                                                  \-> (cancelled / no_show can occur earlier)
-- 'in_queue' is kept as the canonical "waiting in queue" state rather than
-- adding a redundant new 'waiting' label — it already meant exactly that.
--
-- Columns added mirror this pipeline so reception/doctor UIs (which cannot
-- read audit_logs — that table is admin-only) can show real timestamps
-- without a privileged join; audit_logs still gets a row for every
-- transition below via the existing log_audit_event(), for the
-- admin-facing compliance trail.
-- ============================================================================
alter table public.appointments
  add column if not exists patient_arrived_at timestamptz,
  add column if not exists arrival_confirmed_at timestamptz,
  add column if not exists arrival_confirmed_by uuid references auth.users(id) on delete set null,
  add column if not exists called_at timestamptz,
  add column if not exists consultation_started_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists no_show_at timestamptz,
  add column if not exists no_show_by uuid references auth.users(id) on delete set null,
  add column if not exists no_show_reason text;

-- Verified safe before altering: a read-only check against the live
-- database found only 'confirmed' and 'cancelled' in use across the 2
-- appointment rows that currently exist, both already inside the new set.
alter table public.appointments drop constraint if exists appointments_status_check;
alter table public.appointments add constraint appointments_status_check
  check (status in ('confirmed', 'arrived', 'in_queue', 'called', 'in_consultation', 'completed', 'cancelled', 'no_show'));

-- ----------------------------------------------------------------------------
-- patient_arrive_appointment() — the patient's own self-check-in from the
-- app ("I'm here"). Deliberately does NOT assign a queue number: per spec,
-- a queue number must never be shown until the backend actually assigns
-- one, which only happens once reception confirms the arrival (below).
--
-- Check-in window: doctor_schedule.time_slot is free text ("10:30 AM"), not
-- a real time column, so a reliable minute-level window can't be computed
-- server-side without parsing that text. The rule actually enforced here is
-- date-level: only today's own confirmed appointment can be self-checked-in
-- — not a future date, not a past one, not another patient's, not an
-- already-cancelled/completed/no-show one. This is the real, implementable
-- rule given the schema, not the finer-grained window the spec describes
-- conceptually.
-- ----------------------------------------------------------------------------
create or replace function public.patient_arrive_appointment(p_appointment_id uuid)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_appt public.appointments;
begin
  select * into v_appt from public.appointments where id = p_appointment_id;
  if v_appt.id is null then
    raise exception 'Appointment not found.' using errcode = 'P0002';
  end if;

  if auth.uid() is null or auth.uid() <> v_appt.patient_id then
    raise exception 'Not authorized to check in this appointment.' using errcode = '42501';
  end if;

  if v_appt.status <> 'confirmed' then
    raise exception 'This appointment cannot be checked in from its current status.' using errcode = '22023';
  end if;

  if v_appt.appointment_date <> current_date then
    raise exception 'Check-in is only available on the day of your appointment.' using errcode = '22023';
  end if;

  update public.appointments
  set status = 'arrived', patient_arrived_at = now()
  where id = p_appointment_id
  returning * into v_appt;

  perform public.log_audit_event(
    'APPOINTMENT_PATIENT_ARRIVED', 'appointments', v_appt.id, v_appt.patient_id,
    jsonb_build_object('provider_id', v_appt.provider_id)
  );

  return v_appt;
end;
$$;

revoke all on function public.patient_arrive_appointment(uuid) from public;
grant execute on function public.patient_arrive_appointment(uuid) to authenticated;

-- ----------------------------------------------------------------------------
-- check_in_appointment() — reception confirms the patient is physically
-- present and assigns the real queue number, atomically. Now accepts a
-- 'confirmed' appointment too (a walk-up patient reception checks in
-- directly, who never used the app's self-check-in) as well as 'arrived'
-- (the patient already self-declared via the app) — either way this step,
-- not patient_arrive_appointment(), is what actually assigns the queue
-- number, per spec ("do not display a queue number until the backend has
-- actually assigned one").
-- ----------------------------------------------------------------------------
create or replace function public.check_in_appointment(p_appointment_id uuid)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_appt public.appointments;
  v_next_num integer;
begin
  select * into v_appt from public.appointments where id = p_appointment_id;
  if v_appt.id is null then
    raise exception 'Appointment not found.' using errcode = 'P0002';
  end if;

  if not (
    exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = v_appt.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
    or public.is_admin()
  ) then
    raise exception 'Not authorized to check in this appointment.' using errcode = '42501';
  end if;

  if v_appt.status not in ('confirmed', 'arrived') then
    raise exception 'Only a confirmed or arrived appointment can be checked in.' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtext(coalesce(v_appt.provider_id::text, 'none') || v_appt.appointment_date::text));

  select count(*) + 1 into v_next_num
  from public.appointments
  where provider_id is not distinct from v_appt.provider_id
    and appointment_date = v_appt.appointment_date
    and queue_number is not null;

  update public.appointments
  set status = 'in_queue',
      queue_number = 'A' || lpad(v_next_num::text, 3, '0'),
      arrival_confirmed_at = now(),
      arrival_confirmed_by = auth.uid()
  where id = p_appointment_id
  returning * into v_appt;

  perform public.create_notification(
    v_appt.patient_id, 'appointments', 'You have been checked in',
    'Queue number ' || v_appt.queue_number || ' — ' || v_appt.doctor_name, 'appointments', v_appt.id
  );

  perform public.log_audit_event(
    'APPOINTMENT_ARRIVAL_CONFIRMED', 'appointments', v_appt.id, v_appt.patient_id,
    jsonb_build_object('provider_id', v_appt.provider_id, 'queue_number', v_appt.queue_number)
  );

  return v_appt;
end;
$$;

revoke all on function public.check_in_appointment(uuid) from public;
grant execute on function public.check_in_appointment(uuid) to authenticated;

-- ----------------------------------------------------------------------------
-- call_patient() — reception or the treating doctor calls the next
-- patient. Only from 'in_queue' (must have a real queue position first).
-- ----------------------------------------------------------------------------
create or replace function public.call_patient(p_appointment_id uuid)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_appt public.appointments;
begin
  select * into v_appt from public.appointments where id = p_appointment_id;
  if v_appt.id is null then
    raise exception 'Appointment not found.' using errcode = 'P0002';
  end if;

  if not (
    exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = v_appt.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
    or exists (
      select 1 from public.doctor_profiles dp where dp.id = v_appt.doctor_profile_id and dp.user_id = auth.uid()
    )
    or public.is_admin()
  ) then
    raise exception 'Not authorized to call this patient.' using errcode = '42501';
  end if;

  if v_appt.status <> 'in_queue' then
    raise exception 'Only a patient currently in the queue can be called.' using errcode = '22023';
  end if;

  update public.appointments
  set status = 'called', called_at = now()
  where id = p_appointment_id
  returning * into v_appt;

  perform public.create_notification(
    v_appt.patient_id, 'appointments', 'Your appointment is ready',
    v_appt.doctor_name || ' is ready to see you. Please proceed to the consultation area.',
    'appointments', v_appt.id
  );

  perform public.log_audit_event(
    'APPOINTMENT_PATIENT_CALLED', 'appointments', v_appt.id, v_appt.patient_id,
    jsonb_build_object('provider_id', v_appt.provider_id)
  );

  return v_appt;
end;
$$;

revoke all on function public.call_patient(uuid) from public;
grant execute on function public.call_patient(uuid) to authenticated;

-- ----------------------------------------------------------------------------
-- start_consultation() — the treating doctor begins seeing the patient.
-- Called alongside (not instead of) the existing encounters.startEncounter()
-- client call — encounters already carries the real clinical workflow; this
-- only keeps appointments.status in sync so reception/patient views (which
-- read appointments, not encounters) reflect it. Allowed from 'in_queue' too
-- (a doctor pulling the next patient without reception having called them
-- first — a real small clinic workflow) as well as 'called'.
-- ----------------------------------------------------------------------------
create or replace function public.start_consultation(p_appointment_id uuid)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_appt public.appointments;
begin
  select * into v_appt from public.appointments where id = p_appointment_id;
  if v_appt.id is null then
    raise exception 'Appointment not found.' using errcode = 'P0002';
  end if;

  if not (
    exists (
      select 1 from public.doctor_profiles dp where dp.id = v_appt.doctor_profile_id and dp.user_id = auth.uid()
    )
    or public.is_admin()
  ) then
    raise exception 'Not authorized to start this consultation.' using errcode = '42501';
  end if;

  if v_appt.status not in ('in_queue', 'called') then
    raise exception 'Only a waiting or called patient can start a consultation.' using errcode = '22023';
  end if;

  update public.appointments
  set status = 'in_consultation', consultation_started_at = now()
  where id = p_appointment_id
  returning * into v_appt;

  perform public.log_audit_event(
    'APPOINTMENT_CONSULTATION_STARTED', 'appointments', v_appt.id, v_appt.patient_id,
    jsonb_build_object('provider_id', v_appt.provider_id)
  );

  return v_appt;
end;
$$;

revoke all on function public.start_consultation(uuid) from public;
grant execute on function public.start_consultation(uuid) to authenticated;

-- ----------------------------------------------------------------------------
-- complete_appointment_visit() — marks the appointment itself completed.
-- Named distinctly from encounters' own 'completed' status (different
-- table, different concept) — called alongside encounters.completeEncounter()
-- when that encounter has a real appointment_id, so appointments.status
-- (what reception/patient views read) stays in sync with the encounter
-- (what the Health Journey already reads — no change needed there).
-- ----------------------------------------------------------------------------
create or replace function public.complete_appointment_visit(p_appointment_id uuid)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_appt public.appointments;
begin
  select * into v_appt from public.appointments where id = p_appointment_id;
  if v_appt.id is null then
    raise exception 'Appointment not found.' using errcode = 'P0002';
  end if;

  if not (
    exists (
      select 1 from public.doctor_profiles dp where dp.id = v_appt.doctor_profile_id and dp.user_id = auth.uid()
    )
    or public.is_admin()
  ) then
    raise exception 'Not authorized to complete this appointment.' using errcode = '42501';
  end if;

  if v_appt.status <> 'in_consultation' then
    raise exception 'Only an appointment currently in consultation can be completed.' using errcode = '22023';
  end if;

  update public.appointments
  set status = 'completed', completed_at = now()
  where id = p_appointment_id
  returning * into v_appt;

  perform public.create_notification(
    v_appt.patient_id, 'appointments', 'Appointment completed',
    'Your visit with ' || v_appt.doctor_name || ' is complete.', 'appointments', v_appt.id
  );

  perform public.log_audit_event(
    'APPOINTMENT_COMPLETED', 'appointments', v_appt.id, v_appt.patient_id,
    jsonb_build_object('provider_id', v_appt.provider_id)
  );

  return v_appt;
end;
$$;

revoke all on function public.complete_appointment_visit(uuid) from public;
grant execute on function public.complete_appointment_visit(uuid) to authenticated;

-- ----------------------------------------------------------------------------
-- mark_appointment_no_show() — reception marks a patient absent.
--
-- Proposed rule (no configured grace-period exists anywhere in this schema,
-- so this is the smallest defensible rule derivable from the data model,
-- not an invented precise minute threshold): a no-show can only be marked
-- (a) on or after the appointment's own date — never for a future visit —
-- and (b) while the appointment is still 'confirmed' or 'arrived', i.e. the
-- patient never actually reached the queue. Once reception has confirmed
-- arrival (in_queue) or later, the patient plainly did show up, so no-show
-- no longer applies. This prevents the "arbitrary immediate no-show
-- marking" the spec explicitly warns against, without inventing a specific
-- number of minutes nobody has configured.
-- ----------------------------------------------------------------------------
create or replace function public.mark_appointment_no_show(p_appointment_id uuid, p_reason text default null)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_appt public.appointments;
begin
  select * into v_appt from public.appointments where id = p_appointment_id;
  if v_appt.id is null then
    raise exception 'Appointment not found.' using errcode = 'P0002';
  end if;

  if not (
    exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = v_appt.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
    or public.is_admin()
  ) then
    raise exception 'Not authorized to mark this appointment as no-show.' using errcode = '42501';
  end if;

  if v_appt.status not in ('confirmed', 'arrived') then
    raise exception 'Only a confirmed or arrived appointment that has not reached the queue can be marked no-show.' using errcode = '22023';
  end if;

  if v_appt.appointment_date > current_date then
    raise exception 'A future appointment cannot be marked no-show yet.' using errcode = '22023';
  end if;

  update public.appointments
  set status = 'no_show', no_show_at = now(), no_show_by = auth.uid(), no_show_reason = p_reason
  where id = p_appointment_id
  returning * into v_appt;

  perform public.log_audit_event(
    'APPOINTMENT_NO_SHOW', 'appointments', v_appt.id, v_appt.patient_id,
    jsonb_build_object('provider_id', v_appt.provider_id, 'reason', p_reason)
  );

  return v_appt;
end;
$$;

revoke all on function public.mark_appointment_no_show(uuid, text) from public;
grant execute on function public.mark_appointment_no_show(uuid, text) to authenticated;

-- ============================================================================
-- ITEM 2 of 6: Facility departments + services
-- Source: supabase/migrations/20260902015936_facility_departments_services.sql
-- ============================================================================

-- ============================================================================
-- NiaCare — Facility departments, services, and doctor-department assignment
--
-- STATUS: NOT YET APPLIED to the live database as of this file's creation.
-- Extracted verbatim from supabase/schema.sql (byte-identical to that
-- section) so it can be reviewed and applied on its own.
--
-- DEPENDENCY: none. This migration does not depend on any of the other
-- currently-pending migrations (appointment pipeline,
-- fetch_patient_record_access_log, fetch_queue_position) — it only
-- references providers, provider_staff, doctor_profiles, is_admin(),
-- set_updated_at(), and log_audit_event(), all of which are already live.
-- It can be applied independently, in any order relative to those three.
--
-- WHAT THIS ADDS (all additive, nothing removed or renamed):
--   1. facility_departments — new table. A department belongs to exactly
--      one facility (provider_id not null, cascade on facility delete).
--      RLS: active departments are publicly viewable; inactive ones only
--      to admin, that facility's own active staff, or a doctor at that
--      facility. Insert/update restricted to admin or that facility's own
--      active staff. No delete policy — deactivate (is_active = false)
--      instead, per spec ("prefer deactivation").
--   2. facility_services — new table. department_id is nullable (a
--      service like "Emergency" need not map to one department). Same RLS
--      shape as facility_departments.
--   3. doctor_profiles.department_id — new nullable column (a single FK,
--      not a join table — see the in-file comment for why: mirrors the
--      existing one-doctor-one-facility model rather than guessing at a
--      multiplicity nothing else in the schema has yet).
--   4. assign_doctor_department() — a new function, not a broadened
--      doctor_profiles RLS policy. provider_staff has no other write
--      access to doctor_profiles; this function updates only
--      department_id, only for admin / the doctor's own facility staff /
--      the doctor themselves, and only into a department that actually
--      belongs to the doctor's own facility.
--
-- WHY THIS IS SAFE:
--   - Every CREATE TABLE uses IF NOT EXISTS; every trigger/policy is
--     dropped and re-created by name, so re-running this file is a no-op.
--   - Both new tables start empty — there is no existing data that could
--     violate the (provider_id, name) uniqueness constraint or any FK.
--   - RLS is enabled on both tables from creation; there is no window
--     where they exist without it.
--   - department/service management deliberately reuses the exact same
--     "active provider_staff at this provider_id" authorization check
--     already used throughout this schema (check_in_appointment,
--     call_patient, mark_appointment_no_show, etc.) rather than inventing
--     a new authorization model.
--
-- HOW TO APPLY: same process as the other pending migrations — Supabase
-- SQL Editor, after running the pre-flight checks below. Not executed by
-- the assistant that generated this file.
--
-- PRE-FLIGHT (read-only, run first):
--   select count(*) from information_schema.tables
--   where table_schema = 'public' and table_name in ('facility_departments', 'facility_services');
--   -- expect 0 (neither table exists yet); if not 0, stop and inspect
--   -- what's already there before applying.
--
-- POST-DEPLOY VERIFICATION:
--   select table_name from information_schema.tables
--   where table_schema = 'public' and table_name in ('facility_departments', 'facility_services');
--   -- expect both rows.
--   select column_name from information_schema.columns
--   where table_schema = 'public' and table_name = 'doctor_profiles' and column_name = 'department_id';
--   -- expect 1 row.
--   select proname from pg_proc where pronamespace = 'public'::regnamespace and proname = 'assign_doctor_department';
--   -- expect 1 row.
-- ============================================================================

-- ============================================================================
-- FACILITY DEPARTMENTS — a department belongs to exactly one facility.
--
-- provider_staff.permissions (text[]) exists but is never read anywhere in
-- this codebase (checked — no RLS policy, no RPC, no frontend code
-- references it at all). Rather than invent fine-grained permission
-- checking on top of an unused column, department/service management here
-- uses the same coarse "any active staff member at this facility" gate
-- every other provider_staff-scoped RPC already uses (check_in_appointment,
-- call_patient, mark_appointment_no_show, etc.) — consistent with existing
-- precedent, not a new, weaker, or stricter standard.
-- ============================================================================
create table if not exists public.facility_departments (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references public.providers(id) on delete cascade,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_id, name)
);

create index if not exists facility_departments_provider_id_idx on public.facility_departments(provider_id);

alter table public.facility_departments enable row level security;

-- Active departments are public (a patient browsing a facility profile
-- should see them without needing any relationship to that facility);
-- inactive ones are visible only to admin, that facility's own staff, or a
-- doctor who actually belongs to that facility — never to patients or
-- unrelated doctors/staff.
drop policy if exists "Facility departments are viewable" on public.facility_departments;
create policy "Facility departments are viewable"
  on public.facility_departments for select
  using (
    is_active
    or public.is_admin()
    or exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = facility_departments.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
    or exists (
      select 1 from public.doctor_profiles dp
      where dp.provider_id = facility_departments.provider_id and dp.user_id = auth.uid()
    )
  );

drop policy if exists "Facility departments are manageable by facility staff or admin" on public.facility_departments;
create policy "Facility departments are manageable by facility staff or admin"
  on public.facility_departments for insert
  with check (
    public.is_admin()
    or exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = facility_departments.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
  );

drop policy if exists "Facility departments are updatable by facility staff or admin" on public.facility_departments;
create policy "Facility departments are updatable by facility staff or admin"
  on public.facility_departments for update
  using (
    public.is_admin()
    or exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = facility_departments.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
  )
  with check (
    public.is_admin()
    or exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = facility_departments.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
  );

-- No delete policy anywhere: per spec, "prefer deactivation" — a department
-- can be deactivated (is_active = false) by facility staff/admin, but
-- deletion (which would cascade into facility_services and null out
-- doctor_profiles.department_id) is left to a human running SQL directly
-- with full knowledge of what depends on it, not exposed as an app action.

drop trigger if exists set_facility_departments_updated_at on public.facility_departments;
create trigger set_facility_departments_updated_at
  before update on public.facility_departments
  for each row execute function public.set_updated_at();

-- ============================================================================
-- FACILITY SERVICES — department_id is nullable: a service like "Emergency"
-- or "Pharmacy" may not map to one department, per spec ("Do not make
-- department_id mandatory if some services operate across departments").
-- ============================================================================
create table if not exists public.facility_services (
  id uuid primary key default gen_random_uuid(),
  provider_id uuid not null references public.providers(id) on delete cascade,
  department_id uuid references public.facility_departments(id) on delete set null,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider_id, name)
);

create index if not exists facility_services_provider_id_idx on public.facility_services(provider_id);
create index if not exists facility_services_department_id_idx on public.facility_services(department_id);

alter table public.facility_services enable row level security;

drop policy if exists "Facility services are viewable" on public.facility_services;
create policy "Facility services are viewable"
  on public.facility_services for select
  using (
    is_active
    or public.is_admin()
    or exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = facility_services.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
    or exists (
      select 1 from public.doctor_profiles dp
      where dp.provider_id = facility_services.provider_id and dp.user_id = auth.uid()
    )
  );

drop policy if exists "Facility services are manageable by facility staff or admin" on public.facility_services;
create policy "Facility services are manageable by facility staff or admin"
  on public.facility_services for insert
  with check (
    public.is_admin()
    or exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = facility_services.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
  );

drop policy if exists "Facility services are updatable by facility staff or admin" on public.facility_services;
create policy "Facility services are updatable by facility staff or admin"
  on public.facility_services for update
  using (
    public.is_admin()
    or exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = facility_services.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
  )
  with check (
    public.is_admin()
    or exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = facility_services.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
  );

drop trigger if exists set_facility_services_updated_at on public.facility_services;
create trigger set_facility_services_updated_at
  before update on public.facility_services
  for each row execute function public.set_updated_at();

-- ============================================================================
-- DOCTOR → DEPARTMENT — a single nullable column, not a join table.
--
-- Chosen deliberately after inspecting the existing model: doctor_profiles
-- is already one-doctor-one-facility (provider_id), so "one doctor, one
-- department at that facility" mirrors the existing architecture rather
-- than introducing a new multiplicity the rest of the schema doesn't have.
-- If NiaCare later needs a doctor to belong to multiple departments at once
-- (e.g. a physician covering both Internal Medicine and Cardiology), that
-- needs a real join table (doctor_department_memberships or similar) —
-- documented here as a future decision, not guessed at now.
-- ============================================================================
alter table public.doctor_profiles
  add column if not exists department_id uuid references public.facility_departments(id) on delete set null;

-- assign_doctor_department() — deliberately a function, not a broadened
-- doctor_profiles RLS policy. provider_staff currently has NO update access
-- to doctor_profiles at all (only the doctor themselves or an admin can
-- update that table — see "Doctors can update own profile" /
-- "Admins can manage doctor profiles" above); granting a blanket new
-- provider_staff UPDATE policy on all of doctor_profiles would let facility
-- staff rewrite a doctor's bio/fees/specialty too, well beyond "assign to a
-- department". This function does exactly one thing: validates the caller
-- is admin, the doctor's own facility staff, or the doctor themselves, and
-- that the target department (if any) actually belongs to the SAME
-- facility as the doctor — then updates only department_id.
create or replace function public.assign_doctor_department(p_doctor_profile_id uuid, p_department_id uuid default null)
returns public.doctor_profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_doctor public.doctor_profiles;
  v_dept public.facility_departments;
begin
  select * into v_doctor from public.doctor_profiles where id = p_doctor_profile_id;
  if v_doctor.id is null then
    raise exception 'Doctor profile not found.' using errcode = 'P0002';
  end if;

  if not (
    public.is_admin()
    or v_doctor.user_id = auth.uid()
    or exists (
      select 1 from public.provider_staff ps
      where ps.provider_id = v_doctor.provider_id and ps.user_id = auth.uid() and ps.is_active = true
    )
  ) then
    raise exception 'Not authorized to assign this doctor to a department.' using errcode = '42501';
  end if;

  if p_department_id is not null then
    select * into v_dept from public.facility_departments where id = p_department_id;
    if v_dept.id is null then
      raise exception 'Department not found.' using errcode = 'P0002';
    end if;
    if v_dept.provider_id is distinct from v_doctor.provider_id then
      raise exception 'That department belongs to a different facility.' using errcode = '22023';
    end if;
  end if;

  update public.doctor_profiles
  set department_id = p_department_id
  where id = p_doctor_profile_id
  returning * into v_doctor;

  perform public.log_audit_event(
    'DOCTOR_PROFILE_UPDATED', 'doctor_profiles', v_doctor.id, null,
    jsonb_build_object('department_id', p_department_id, 'action', 'department_assigned')
  );

  return v_doctor;
end;
$$;

revoke all on function public.assign_doctor_department(uuid, uuid) from public;
grant execute on function public.assign_doctor_department(uuid, uuid) to authenticated;

-- ============================================================================
-- ITEM 3 of 6: book_appointment() active-facility/active-doctor check
-- Source: supabase/migrations/20260902041602_book_appointment_active_check.sql
-- ============================================================================

-- ============================================================================
-- NiaCare — book_appointment(): reject bookings against an inactive
-- facility or inactive doctor.
--
-- STATUS: NOT YET APPLIED to the live database as of this file's creation.
--
-- IMPORTANT DIFFERENCE FROM THE OTHER PENDING MIGRATIONS: book_appointment()
-- is ALREADY LIVE and already in active use (it is NOT one of the pending,
-- not-yet-deployed functions). This migration REPLACES its body — same
-- name, same signature (CREATE OR REPLACE, so no client code needs to
-- change) — adding two new checks near the top. Applying this migration
-- changes real, already-live behavior: a booking attempt against a
-- deactivated facility or a deactivated doctor will start being rejected
-- with a clear error where it previously would have silently succeeded.
-- Every other migration in this directory only adds new, previously-absent
-- objects; this one modifies an existing one. Review accordingly.
--
-- WHY: reviewed while auditing facility/doctor activation — providers and
-- doctor_profiles both already have is_active, and the UI already lets an
-- admin deactivate either one, but nothing enforced that a deactivated
-- facility/doctor stop receiving NEW bookings. The existing RLS policy on
-- appointments ("Appointments are manageable by owner") does not check
-- providers.is_active or doctor_profiles.is_active at all, so this had to
-- be added inside the RPC itself, per spec ("implement it at the
-- RPC/database level, not only in the UI").
--
-- WHAT IS NOT CHANGED: the function's signature, its schedule-slot
-- reservation logic (the ON CONFLICT ... WHERE is_booked = false upsert),
-- its notification call, and its authorization check are all byte-for-byte
-- identical to the current live version. Only two new IF blocks were
-- inserted, both purely rejecting (raising an exception) — neither can
-- cause an otherwise-valid booking to succeed differently than before.
--
-- PRE-FLIGHT (read-only, run first):
--   select count(*) from public.providers where is_active = false;
--   select count(*) from public.doctor_profiles where is_active = false;
--   -- Informational only — tells you how many facilities/doctors would
--   -- start rejecting new bookings once this is applied. Neither query
--   -- blocks applying the migration; review the results before deciding
--   -- whether any of those facilities/doctors should be reactivated first
--   -- if the deactivation was unintentional.
--
-- POST-DEPLOY VERIFICATION:
--   select prosrc from pg_proc
--   where pronamespace = 'public'::regnamespace and proname = 'book_appointment';
--   -- expect: the returned text contains
--   --   "This facility is not currently accepting new appointments"
--   --   and "This doctor is not currently accepting new appointments".
-- ============================================================================

create or replace function public.book_appointment(
  p_patient_id uuid,
  p_ticket_number text,
  p_doctor_id text,
  p_doctor_name text,
  p_doctor_specialty text,
  p_hospital_name text,
  p_hospital_location text,
  p_room_number text,
  p_consultation_type text,
  p_appointment_date date,
  p_time_slot text,
  p_queue_number text,
  p_reason text,
  p_symptoms_note text,
  p_insurance_provider text,
  p_insurance_covered boolean,
  p_co_pay_amount_tzs integer,
  p_patient_name text,
  p_patient_phone text,
  p_provider_id uuid default null,
  p_doctor_profile_id uuid default null
)
returns public.appointments
language plpgsql
security definer
set search_path = public
as $$
declare
  v_appointment public.appointments;
  v_doctor_user_id uuid;
begin
  if auth.uid() is null or auth.uid() <> p_patient_id then
    raise exception 'Not authorized to book this appointment.' using errcode = '42501';
  end if;

  -- A deactivated facility/doctor must not receive new bookings. Checked
  -- here, not only in the UI, per spec — a raw RPC call (or a UI bug) must
  -- not be able to bypass this. Only checked when a real provider/doctor is
  -- attached (p_provider_id/p_doctor_profile_id are both nullable — the
  -- pre-real-doctors static directory path has neither).
  if p_provider_id is not null and not exists (
    select 1 from public.providers where id = p_provider_id and is_active = true
  ) then
    raise exception 'This facility is not currently accepting new appointments.' using errcode = '22023';
  end if;

  if p_doctor_profile_id is not null and not exists (
    select 1 from public.doctor_profiles where id = p_doctor_profile_id and is_active = true
  ) then
    raise exception 'This doctor is not currently accepting new appointments.' using errcode = '22023';
  end if;

  if p_doctor_profile_id is not null then
    insert into public.doctor_schedule (doctor_profile_id, schedule_date, time_slot, is_booked)
    values (p_doctor_profile_id, p_appointment_date, p_time_slot, true)
    on conflict (doctor_profile_id, schedule_date, time_slot)
    do update set is_booked = true
    where doctor_schedule.is_booked = false;

    if not found then
      raise exception 'This time slot is no longer available.' using errcode = '23505';
    end if;
  end if;

  insert into public.appointments (
    patient_id, provider_id, doctor_profile_id, ticket_number, doctor_id, doctor_name,
    doctor_specialty, hospital_name, hospital_location, room_number, consultation_type,
    appointment_date, time_slot, status, queue_number, reason, symptoms_note,
    insurance_provider, insurance_covered, co_pay_amount_tzs, patient_name, patient_phone
  ) values (
    p_patient_id, p_provider_id, p_doctor_profile_id, p_ticket_number, p_doctor_id, p_doctor_name,
    p_doctor_specialty, p_hospital_name, p_hospital_location, p_room_number, p_consultation_type,
    p_appointment_date, p_time_slot, 'confirmed', p_queue_number, p_reason, p_symptoms_note,
    p_insurance_provider, p_insurance_covered, p_co_pay_amount_tzs, p_patient_name, p_patient_phone
  )
  returning * into v_appointment;

  if p_doctor_profile_id is not null then
    update public.doctor_schedule
    set appointment_id = v_appointment.id
    where doctor_profile_id = p_doctor_profile_id
      and schedule_date = p_appointment_date
      and time_slot = p_time_slot;

    select user_id into v_doctor_user_id from public.doctor_profiles where id = p_doctor_profile_id;
    if v_doctor_user_id is not null then
      perform public.create_notification(
        v_doctor_user_id, 'appointments', 'New appointment booked',
        coalesce(p_patient_name, 'A patient') || ' — ' || p_appointment_date || ' at ' || p_time_slot,
        'appointments', v_appointment.id
      );
    end if;
  end if;

  return v_appointment;
end;
$$;

revoke all on function public.book_appointment(
  uuid, text, text, text, text, text, text, text, text, date, text, text, text, text, text,
  boolean, integer, text, text, uuid, uuid
) from public;
grant execute on function public.book_appointment(
  uuid, text, text, text, text, text, text, text, text, date, text, text, text, text, text,
  boolean, integer, text, text, uuid, uuid
) to authenticated;

-- ============================================================================
-- ITEM 4 of 6: fetch_queue_position()
-- Source: supabase/schema.sql (not a standalone migration file)
-- Depends on item 1 above (appointments.called_at, 'called'/'in_consultation' statuses)
-- ============================================================================

-- fetch_queue_position() — patient-facing "how many people are ahead of me"
-- for the queue status strip.
--
-- Fixes a real gap found while reviewing this: the client-side version of
-- this query (still in src/lib/queue.ts before this function existed) reads
-- public.appointments directly, and this table's only RLS policy is
-- "own row, or treating doctor, or facility staff, or admin" — a patient
-- querying other patients' rows for the same provider/date to count how
-- many are ahead of them would get zero rows back, silently. That made
-- "patients ahead" and "now serving" always come back 0/empty for every
-- patient, every time, well before this change. This function returns only
-- an aggregate count and other patients' ticket numbers (never names,
-- phones, reasons, or any clinical field) via SECURITY DEFINER, which is
-- the narrow fix — not a broadened table-level RLS policy, which would let
-- any signed-in patient read full appointment rows for a whole facility.
-- ----------------------------------------------------------------------------
create or replace function public.fetch_queue_position(
  p_provider_id uuid,
  p_appointment_date date,
  p_my_queue_number text
)
returns table (
  patients_ahead integer,
  now_serving text,
  currently_serving text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not authorized.' using errcode = '42501';
  end if;

  return query
  select
    (select count(*)::integer from public.appointments a
     where a.provider_id is not distinct from p_provider_id
       and a.appointment_date = p_appointment_date
       and a.status = 'in_queue'
       and a.queue_number is not null
       and a.queue_number < p_my_queue_number),
    (select a.queue_number from public.appointments a
     where a.provider_id is not distinct from p_provider_id
       and a.appointment_date = p_appointment_date
       and a.status = 'in_queue'
       and a.queue_number is not null
     order by a.queue_number asc
     limit 1),
    (select a.queue_number from public.appointments a
     where a.provider_id is not distinct from p_provider_id
       and a.appointment_date = p_appointment_date
       and a.status in ('called', 'in_consultation')
       and a.queue_number is not null
     order by a.called_at desc nulls last
     limit 1);
end;
$$;

revoke all on function public.fetch_queue_position(uuid, date, text) from public;
grant execute on function public.fetch_queue_position(uuid, date, text) to authenticated;

-- ============================================================================
-- ITEM 5 of 6: fetch_patient_record_access_log()
-- Source: supabase/schema.sql (not a standalone migration file)
-- ============================================================================

-- ============================================================================
-- fetch_patient_record_access_log() — a minimal, patient-safe read path
-- into audit_logs for the "who accessed my records" screen.
--
-- audit_logs itself stays admin-only (its RLS is NOT touched or widened —
-- this function reads it via SECURITY DEFINER instead, the same pattern
-- already used elsewhere in this schema for a narrow authorized read). Two
-- deliberate restrictions keep this from becoming a second, looser way to
-- read the whole table: (a) it always filters to `patient_id = auth.uid()`
-- — a caller can only ever get their own rows, no parameter can widen that;
-- (b) it excludes the caller's own actions (`actor_id is distinct from
-- patient_id`) and only returns a fixed allow-list of "someone accessed my
-- clinical data" action types — not every audit_logs row concerning this
-- patient (e.g. appointment/queue events aren't clinical record access and
-- are deliberately left out), and never the raw `metadata` column.
-- ============================================================================
create or replace function public.fetch_patient_record_access_log(p_limit integer default 30)
returns table (
  id uuid,
  actor_name text,
  action text,
  accessed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not authorized.' using errcode = '42501';
  end if;

  return query
  select al.id, coalesce(p.full_name, 'Care team member') as actor_name, al.action, al.created_at
  from public.audit_logs al
  left join public.profiles p on p.id = al.actor_id
  where al.patient_id = auth.uid()
    and al.actor_id is distinct from al.patient_id
    and al.action in ('CLINICAL_RECORD_ACCESSED', 'MEDICAL_RECORD_VIEWED', 'IMAGING_ACCESSED', 'LAB_RESULT_VIEWED')
  order by al.created_at desc
  limit greatest(1, least(p_limit, 100));
end;
$$;

revoke all on function public.fetch_patient_record_access_log(integer) from public;
grant execute on function public.fetch_patient_record_access_log(integer) to authenticated;


-- ============================================================================
-- ITEM 6 of 6: audit_logs.facility_id + log_audit_event() facility parameter
-- Source: supabase/migrations/20260902045354_audit_logs_facility_id.sql
-- ============================================================================

-- ============================================================================
-- NiaCare — audit_logs.facility_id + log_audit_event() facility parameter
--
-- STATUS: NOT YET APPLIED to the live database as of this file's creation.
--
-- IMPORTANT — same category as the book_appointment() migration, NOT the
-- purely-additive ones: this REPLACES an already-live function,
-- log_audit_event(text, text, uuid, uuid, jsonb), which is in active use
-- throughout this schema (referrals, record access requests, role changes,
-- and — once deployed — the appointment pipeline). It is dropped and
-- recreated with a 6th, optional, defaulted parameter (p_facility_id).
--
-- WHY DROP + CREATE, NOT PLAIN CREATE OR REPLACE: Postgres identifies a
-- function by name AND parameter list — CREATE OR REPLACE with a different
-- parameter list does not replace an existing function, it adds a second,
-- overloaded one. Two overloads whose only difference is a trailing
-- default parameter break PostgREST's RPC dispatch (PGRST203, "could not
-- choose the best candidate function") for calls that omit that parameter
-- — which is every existing call site in this app. Dropping the old 5-arg
-- signature first avoids that entirely: exactly one function exists
-- afterward, and every existing caller (positional SQL calls throughout
-- schema.sql, and the frontend's named-argument logAuditEvent() calls)
-- keeps working unchanged, since the new parameter defaults to null.
--
-- WHY: found while extending the admin Audit panel with a facility filter.
-- The existing approach would have been parsing metadata.provider_id
-- (already present on some, not all, audit_logs rows) client-side, with no
-- index — fragile and explicitly against this phase's own instruction to
-- introduce a real column instead. facility_id is a plain nullable FK, not
-- required on any event (most audit events — record access, role changes —
-- aren't facility-scoped at all).
--
-- WHAT IS NOT CHANGED: audit_logs' existing columns, its admin-only RLS
-- policy (re-stated here only because it sits between the two changes in
-- schema.sql, not because it's different), and every other function in
-- this schema. Existing rows are untouched — facility_id is simply null on
-- all of them until new events populate it.
--
-- DEPENDENCY: none on the other 4 pending migrations — independent.
--
-- PRE-FLIGHT (read-only, run first):
--   select count(*) from information_schema.columns
--   where table_schema = 'public' and table_name = 'audit_logs' and column_name = 'facility_id';
--   -- expect 0 (column doesn't exist yet).
--   select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
--   where n.nspname = 'public' and p.proname = 'log_audit_event';
--   -- expect 1 (the current 5-arg version) — confirms there isn't already
--   -- an unexpected overload before this migration adds its own.
--
-- POST-DEPLOY VERIFICATION:
--   select column_name from information_schema.columns
--   where table_schema = 'public' and table_name = 'audit_logs' and column_name = 'facility_id';
--   -- expect 1 row.
--   select p.proname, pg_get_function_identity_arguments(p.oid) as args
--   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
--   where n.nspname = 'public' and p.proname = 'log_audit_event';
--   -- expect exactly 1 row, args ending in "... jsonb, facility_id uuid".
--   -- If 2 rows appear, the DROP did not take effect — investigate before
--   -- relying on this function; do not leave two overloads live.
--   select indexname from pg_indexes where schemaname = 'public' and indexname = 'audit_logs_facility_id_idx';
--   -- expect 1 row.
-- ============================================================================

-- facility_id: a real column, not fragile client-side metadata.provider_id
-- parsing (which some but not all existing log_audit_event() calls happen
-- to set, inconsistently, inside a jsonb blob with no index). Nullable —
-- most audit events (record access, role changes) aren't facility-scoped
-- at all, so this is never mandatory.
alter table public.audit_logs
  add column if not exists facility_id uuid references public.providers(id) on delete set null;

create index if not exists audit_logs_facility_id_idx on public.audit_logs(facility_id);

alter table public.audit_logs enable row level security;

drop policy if exists "Audit logs are viewable by admins only" on public.audit_logs;
create policy "Audit logs are viewable by admins only"
  on public.audit_logs for select
  using (public.is_admin());

-- p_facility_id appended as a new, optional, defaulted last parameter.
-- IMPORTANT: this must be a DROP + CREATE, not a plain CREATE OR REPLACE —
-- log_audit_event(text, text, uuid, uuid, jsonb) is already live and in
-- active use throughout this schema. Postgres treats a different
-- parameter LIST as a different function identity, so CREATE OR REPLACE
-- alone would leave the old 5-arg version in place and add this as a
-- second, overloaded function — which breaks PostgREST's RPC dispatch
-- (it cannot choose between two overloads whose only difference is a
-- trailing default parameter, and returns PGRST203 "could not choose the
-- best candidate function" for exactly the calls this app already makes).
-- Dropping the old 5-arg signature first, then creating the 6-arg
-- replacement, leaves exactly one function — every existing 5-argument
-- caller (positional SQL calls throughout this file, and the frontend's
-- named-argument logAuditEvent() calls) continues to work unchanged
-- because the 6th parameter defaults to null.
drop function if exists public.log_audit_event(text, text, uuid, uuid, jsonb);

create or replace function public.log_audit_event(
  p_action text,
  p_resource_type text,
  p_resource_id uuid default null,
  p_patient_id uuid default null,
  p_metadata jsonb default '{}'::jsonb,
  p_facility_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs (actor_id, action, resource_type, resource_id, patient_id, metadata, facility_id)
  values (auth.uid(), p_action, p_resource_type, p_resource_id, p_patient_id, p_metadata, p_facility_id);
end;
$$;

revoke all on function public.log_audit_event(text, text, uuid, uuid, jsonb, uuid) from public;
grant execute on function public.log_audit_event(text, text, uuid, uuid, jsonb, uuid) to authenticated;

commit;

-- ============================================================================
-- POST-DEPLOY VERIFICATION — run these after the block above completes.
-- Each should return the row(s) noted; if any doesn't, stop and compare
-- against that item's own source file before assuming deployment succeeded.
-- ============================================================================

-- 1. Appointment pipeline
select column_name from information_schema.columns
where table_schema = 'public' and table_name = 'appointments'
  and column_name in ('patient_arrived_at','arrival_confirmed_at','arrival_confirmed_by',
    'called_at','consultation_started_at','completed_at','no_show_at','no_show_by','no_show_reason')
order by 1;
-- expect: 9 rows

select proname from pg_proc
where pronamespace = 'public'::regnamespace
  and proname in ('patient_arrive_appointment','check_in_appointment','call_patient',
    'start_consultation','complete_appointment_visit','mark_appointment_no_show')
order by 1;
-- expect: 6 rows

-- 2. Facility departments/services
select table_name from information_schema.tables
where table_schema = 'public' and table_name in ('facility_departments','facility_services');
-- expect: 2 rows

select column_name from information_schema.columns
where table_schema = 'public' and table_name = 'doctor_profiles' and column_name = 'department_id';
-- expect: 1 row

-- 3. book_appointment active check
select prosrc from pg_proc
where pronamespace = 'public'::regnamespace and proname = 'book_appointment';
-- expect: result contains "currently accepting new appointments"

-- 4 & 5. fetch_queue_position / fetch_patient_record_access_log
select proname, pg_get_function_identity_arguments(oid) as args
from pg_proc
where pronamespace = 'public'::regnamespace
  and proname in ('fetch_queue_position','fetch_patient_record_access_log')
order by 1;
-- expect: 2 rows

-- 6. audit_logs facility_id
select column_name from information_schema.columns
where table_schema = 'public' and table_name = 'audit_logs' and column_name = 'facility_id';
-- expect: 1 row

select proname, pg_get_function_identity_arguments(oid) as args
from pg_proc
where pronamespace = 'public'::regnamespace and proname = 'log_audit_event';
-- expect: EXACTLY 1 row (not 2 — two rows means the DROP in item 6 did not
-- take effect and there are now two ambiguous overloads; investigate
-- immediately, since that breaks every audit-logging call in the app)
